import { BrandIntake } from "./schema";

export const DEFAULT_INTAKE: Partial<BrandIntake> = {
  tagline: "",
  outputPreset: [],
  positioningStatement: "",
  targetAudience: [],
  brandValues: [],
  brandPersonality: [],
  competitorUrls: [],
  colorPreferences: [],
  moodKeywords: [],
  avoidKeywords: [],
  toneAttributes: {
    formal: 5,
    playful: 5,
    bold: 5,
    minimalist: 5,
  },
  voiceCharacteristics: [],
  keyMessages: [],
  uniqueSellingPoints: [],
  platforms: [],
  requiresLogoExploration: false,
  additionalNotes: "",
};

export const PRESET_OPTIONS = {
  industries: [
    "Technology / SaaS",
    "E-commerce / Retail",
    "Healthcare / Wellness",
    "Finance / Fintech",
    "Education / EdTech",
    "Creative / Agency",
    "Food & Beverage",
    "Real Estate",
    "Consulting",
    "Entertainment",
    "Other"
  ],
  outputPresets: [
    { value: "saas-ui", label: "SaaS/UI - Tokens + UI Kit", description: "Design system, components, UI patterns" },
    { value: "ecommerce", label: "E-commerce - Packaging + Imagery", description: "Product photography, packaging, lifestyle" },
    { value: "creator", label: "Creator - Social + Voice", description: "Content templates, social media, personal brand" },
    { value: "directory-seo", label: "Directory / SEO-First Platform", description: "SEO-optimized pages, content structure, listing templates" },
    { value: "marketing-website", label: "Marketing Website / Landing Pages", description: "Landing pages, conversion-focused designs, campaign assets" },
    { value: "content-platform", label: "Content Platform / Blog", description: "Blog templates, article layouts, content hierarchy" },
    { value: "mobile-app", label: "Mobile App Brand", description: "App icon, splash screens, mobile UI patterns, app store assets" },
    { value: "enterprise", label: "Enterprise / B2B Brand", description: "Corporate identity, presentations, documentation templates" },
  ],
  platforms: [
    "Web App",
    "Mobile App",
    "Website",
    "Social Media",
    "Print",
    "Packaging",
    "Presentations",
    "Email"
  ],
  brandValues: [
    "Innovation",
    "Trust",
    "Simplicity",
    "Quality",
    "Sustainability",
    "Community",
    "Empowerment",
    "Transparency",
    "Excellence",
    "Inclusivity"
  ],
  brandPersonalities: [
    "Professional",
    "Friendly",
    "Bold",
    "Sophisticated",
    "Playful",
    "Trustworthy",
    "Innovative",
    "Approachable",
    "Authoritative",
    "Quirky"
  ],
  voiceCharacteristics: [
    "Clear",
    "Concise",
    "Conversational",
    "Educational",
    "Empowering",
    "Enthusiastic",
    "Expert",
    "Friendly",
    "Humorous",
    "Inspirational",
    "Technical",
    "Warm"
  ],
  colors: [
    "Blue",
    "Green",
    "Purple",
    "Red",
    "Orange",
    "Yellow",
    "Pink",
    "Teal",
    "Navy",
    "Black",
    "White",
    "Gray"
  ]
};

export const EXAMPLE_PRESETS: Record<string, Partial<BrandIntake>> = {
  "B2B SaaS": {
    industry: "Technology / SaaS",
    outputPreset: ["saas-ui"],
    brandValues: ["Innovation", "Efficiency", "Trust"],
    brandPersonality: ["Professional", "Innovative", "Reliable"],
    voiceCharacteristics: ["Clear", "Expert", "Concise"],
    colorPreferences: ["Blue", "Navy", "Gray"],
    moodKeywords: ["Professional", "Modern", "Trustworthy", "Efficient"],
    avoidKeywords: ["Casual", "Playful", "Unprofessional"],
    toneAttributes: {
      formal: 7,
      playful: 3,
      bold: 6,
      minimalist: 8,
    },
    platforms: ["Web App", "Website", "Email"],
    requiresLogoExploration: false,
    positioningStatement: "Enterprise-grade tools that help teams work smarter, not harder.",
  },
  "E-commerce Brand": {
    industry: "E-commerce / Retail",
    outputPreset: ["ecommerce"],
    brandValues: ["Quality", "Sustainability", "Customer-First"],
    brandPersonality: ["Friendly", "Trustworthy", "Modern"],
    voiceCharacteristics: ["Conversational", "Warm", "Helpful"],
    colorPreferences: ["Green", "Teal", "White"],
    moodKeywords: ["Premium", "Authentic", "Lifestyle", "Natural"],
    avoidKeywords: ["Cheap", "Generic", "Corporate"],
    toneAttributes: {
      formal: 4,
      playful: 6,
      bold: 7,
      minimalist: 6,
    },
    platforms: ["Website", "Social Media", "Packaging"],
    requiresLogoExploration: true,
    positioningStatement: "Thoughtfully designed products for modern living.",
  },
  "Content Creator": {
    industry: "Creative / Agency",
    outputPreset: ["creator"],
    brandValues: ["Authenticity", "Community", "Empowerment"],
    brandPersonality: ["Friendly", "Approachable", "Enthusiastic"],
    voiceCharacteristics: ["Conversational", "Enthusiastic", "Inspiring"],
    colorPreferences: ["Orange", "Pink", "Purple"],
    moodKeywords: ["Energetic", "Personal", "Relatable", "Vibrant"],
    avoidKeywords: ["Corporate", "Formal", "Boring"],
    toneAttributes: {
      formal: 2,
      playful: 9,
      bold: 8,
      minimalist: 5,
    },
    platforms: ["Social Media", "Website", "Presentations"],
    requiresLogoExploration: false,
    positioningStatement: "Helping creators turn passion into sustainable businesses.",
  },
  "Fintech Startup": {
    industry: "Finance / Fintech",
    outputPreset: ["saas-ui"],
    brandValues: ["Trust", "Transparency", "Innovation"],
    brandPersonality: ["Professional", "Approachable", "Innovative"],
    voiceCharacteristics: ["Clear", "Expert", "Reassuring"],
    colorPreferences: ["Blue", "Navy", "Teal"],
    moodKeywords: ["Secure", "Modern", "Trustworthy", "Accessible"],
    avoidKeywords: ["Complex", "Intimidating", "Old-fashioned"],
    toneAttributes: {
      formal: 6,
      playful: 4,
      bold: 7,
      minimalist: 7,
    },
    platforms: ["Web App", "Mobile App", "Website"],
    requiresLogoExploration: true,
    positioningStatement: "Making financial services accessible, transparent, and human.",
  },
  "Healthcare Brand": {
    industry: "Healthcare / Wellness",
    outputPreset: ["saas-ui", "ecommerce"],
    brandValues: ["Care", "Trust", "Wellness"],
    brandPersonality: ["Caring", "Trustworthy", "Approachable"],
    voiceCharacteristics: ["Warm", "Clear", "Reassuring"],
    colorPreferences: ["Green", "Teal", "Blue"],
    moodKeywords: ["Calming", "Trustworthy", "Natural", "Caring"],
    avoidKeywords: ["Cold", "Clinical", "Intimidating"],
    toneAttributes: {
      formal: 5,
      playful: 3,
      bold: 5,
      minimalist: 7,
    },
    platforms: ["Web App", "Mobile App", "Website"],
    requiresLogoExploration: true,
    positioningStatement: "Your partner in health and wellness, every step of the way.",
  },
  "Creative Agency": {
    industry: "Creative / Agency",
    outputPreset: ["creator", "saas-ui"],
    brandValues: ["Creativity", "Excellence", "Innovation"],
    brandPersonality: ["Bold", "Sophisticated", "Innovative"],
    voiceCharacteristics: ["Bold", "Creative", "Expert"],
    colorPreferences: ["Purple", "Black", "Orange"],
    moodKeywords: ["Bold", "Creative", "Sophisticated", "Modern"],
    avoidKeywords: ["Generic", "Boring", "Corporate"],
    toneAttributes: {
      formal: 5,
      playful: 7,
      bold: 9,
      minimalist: 6,
    },
    platforms: ["Website", "Social Media", "Presentations"],
    requiresLogoExploration: true,
    positioningStatement: "Where creativity meets strategy to build unforgettable brands.",
  },
  "EdTech Platform": {
    industry: "Education / EdTech",
    outputPreset: ["saas-ui", "creator"],
    brandValues: ["Education", "Accessibility", "Empowerment"],
    brandPersonality: ["Friendly", "Educational", "Approachable"],
    voiceCharacteristics: ["Educational", "Encouraging", "Clear"],
    colorPreferences: ["Blue", "Green", "Orange"],
    moodKeywords: ["Inspiring", "Accessible", "Engaging", "Modern"],
    avoidKeywords: ["Boring", "Academic", "Intimidating"],
    toneAttributes: {
      formal: 4,
      playful: 7,
      bold: 6,
      minimalist: 6,
    },
    platforms: ["Web App", "Website", "Social Media"],
    requiresLogoExploration: false,
    positioningStatement: "Making learning accessible, engaging, and effective for everyone.",
  },
  "Consumer Product": {
    industry: "E-commerce / Retail",
    outputPreset: ["ecommerce"],
    brandValues: ["Quality", "Design", "Sustainability"],
    brandPersonality: ["Modern", "Sophisticated", "Friendly"],
    voiceCharacteristics: ["Conversational", "Inspiring", "Warm"],
    colorPreferences: ["Black", "White", "Gray"],
    moodKeywords: ["Minimalist", "Premium", "Modern", "Timeless"],
    avoidKeywords: ["Cheap", "Trendy", "Overdone"],
    toneAttributes: {
      formal: 5,
      playful: 4,
      bold: 6,
      minimalist: 9,
    },
    platforms: ["Website", "Packaging", "Social Media"],
    requiresLogoExploration: true,
    positioningStatement: "Thoughtfully designed products that elevate everyday moments.",
  }
};
